loglevel_unencrypted: debug
opsgenie:
    key: ENC[AES256_GCM,data:kpsSMA9jiIhF0DbmC4rUV+2zCfOGF3+G2x5AudB9SM3+W0+a,iv:6j6XfYbIzd64hQXVqaee69WbSG5ueTWoMYuGY+73tWs=,tag:UxfgbbrmeaRgqrcC7nygGQ==,type:str]
    heartbeat:
        name_unencrypted: xxx.heartbeat
        interval_unencrypted: 5m
ambari:
    interval_unencrypted: 1m
    url_unencrypted: http://localhost:1337/200/critical
    username_unencrypted: user
    password: ENC[AES256_GCM,data:Uijdkg==,iv:0DpfE9NzAbxU83rzR+BcEizciQX2vnvUS9At4rBG+I0=,tag:cD5KSjC2c50Kk8sgXpUz5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10qrzk97esg3lr6pcrgpk82p3sx3k2dqg477ufgx2l3gg564d7gjq2ux9vy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMklOOVUyeHU2NWpZK2cr
            SlE0UXFMM040ZFpqOXZRS0RHWkwzVWg2MEJFCjRZSUx6aXU2YXBRVk8xdnNTVjZS
            Lys2YW1iVXFLTWlOVFYrVE1vS0FYRkUKLS0tIGJmV3pEN0RVbGovalVwM1M0dDFz
            dmhmWFdqcnVYbTlJbUdkNWhETkJaY28KL6QGjp7BDt9aZxRXYWmMgbN17ywFlOtf
            mm7kD70Kpf/vLJ6gQWEotq3ByEfx/QmNQTu3S9CxRdxs70+p92JNDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T09:32:36Z"
    mac: ENC[AES256_GCM,data:rK5Esq5k/7G0VRV2WzkqWx1yxm0pKzVIApuvhZCP+kdtrY9lFBKPem18mWuo6z6WqGHBU5kLl9bpdqDSG6ocUghPk9DTa9s2rOez6Lmu4IRjm6iJ/rwF7ADkYcyKwfzhjX69Kh4a0me/OaCL6R1qSxqmqQGSKP4uItdLgC1Stw4=,iv:0h3eXbST2l7hb6fmrs2Jh1nbXLsuRVYcuuHk1RHbudk=,tag:kBcBVcjnNm3uvaVVmmfJLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
