loglevel_unencrypted: debug
opsgenie:
    key: ENC[AES256_GCM,data:1o9NwVIzG6x6uyv25fCkAtSZRSLqOEdWh0jkz9dLCb9OIU/b,iv:FKQGIOZQad5tldwcxdhgdPXkOHPpnoDWJ/IVEe1ouXk=,tag:rz0614JSM7zhQ+rNHeyqgQ==,type:str]
    heartbeat:
        name_unencrypted: xxx.ambari.alert.heartbeat
        interval_unencrypted: 5m
ambari:
    interval_unencrypted: 1m
    url_unencrypted: http://localhost:1337/200/warning
    username_unencrypted: user
    password: ENC[AES256_GCM,data:LYNTPQ==,iv:jfcszzhutPU6xjJPlyFGGOCw1YtNBoPsSLnpMvd1Bjk=,tag:XbReT1QkfmL9WQ/wES1V+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkvupvkd5a9mtdj4zgrhxqedfjc977a7zkmg37l4x47sadlef3ssesq00g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMXFBcFhiNnAyaHFpRmZh
            M3NyT2VCTVU2Q3phem54UWdqKzA1eEFLclFvCi9FVjZ1aFl3cWMraXpJOC80ZjUw
            MzJqQjhpaWRsditvSExMUU1HNkphKzAKLS0tICtPTkU5Y3g2THdialo2ZTV6VFJr
            YUJsNjRkYVFOSkY0KzRnd056WW1DbDAKDIQWYmcr+UlA2k+EhbNVYYex09cjUSPO
            JmPinr/KA7ipWF5OYTpuZornttQ0iJIUnK4dIDdKz7dd37XwmiEJHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T12:01:20Z"
    mac: ENC[AES256_GCM,data:qkeemuPTQc51zH0K4NOz1+PH7dXsEODDob6u3dwa0CQ+wjFw7Ux/3aEDGqwkdokRaidddTz0J8gHzqGn22CogjpXfKGdIhR5CUGWSqK51kiiU0sVOqvmF/6EpFz4gzvGD2oiEy0ZatW4dv7bgYd2VdhPMkXYH8x6sra4IeNXhuc=,iv:dsZt3Xa3F235LB6Yz4Y5KkQFWocXUqzA2moUP3lx8Zk=,tag:85lammVsdW+Yfv+V7c01lA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
