loglevel_unencrypted: debug
opsgenie:
    key: ENC[AES256_GCM,data:0jkdt1e6WiBs+d6GkTHQqBal0+35UIv3M+r5+etCnd5y2++n,iv:zZxRayqHD/0fMA+1X1SFk7h7DCkNmWiO690juNDL6Dg=,tag:v/66St24SjDVIbGn+Xupcg==,type:str]
    heartbeat:
        name_unencrypted: xxx.ambari.alert.heartbeat
        interval_unencrypted: 5m
ambari:
    interval_unencrypted: 1m
    url_unencrypted: http://localhost:1337/200
    username_unencrypted: user
    password: ENC[AES256_GCM,data:FgWK/A==,iv:O9Cn3Ye+RN3aW4DXLhoEeBXbj5gFwuWdfyBXb/N2GH8=,tag:wMV5E2/YIvfZF5m1XdDAgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkvupvkd5a9mtdj4zgrhxqedfjc977a7zkmg37l4x47sadlef3ssesq00g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWDU0bkIxWEVoMUl6dnlM
            clozcUsyRExDMzhDVkdraDl5a08rdk0veno0Cm9mVUs5bExNYmE3bkxBeDZScEVY
            SGkwSEFUcjVMbWlOOEdWYWhHUCtKcXMKLS0tIHVuZFpHMDZGeGtwaVNHeDlMYUh1
            VXZxQkJtZElxRk4vT2t2Y0MwMHZqWU0K5qKUjg+hbCJPWykv5m7Um5KRfMIsS7bR
            KVMcnerdObaCDeiIdAjNUAnii5VJDCAOasgXSK+ptW0DrrK6jKkEhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T12:00:06Z"
    mac: ENC[AES256_GCM,data:LMx7IbSLd5Z0FDMwUF2MzJyttnH+HrNK6QSt7WoGJELeIqW4D1HOh5wiXUuZYYX2YUbcPX05w8tmCF8Y6A4rtKIsGcB9TecA8mrUCrEByYLo9e/FeRXmRWfU2RG0+oobSu9ShFY9gSd4XPub+78tc/p7jkyCPneerqLJ0Cc7j2U=,iv:fGu5Hge5/0j20Pq7tIV7i2GXqKCYgp3OeEVAg+EtpMA=,tag:I7mOydGoCDJymG+xE2Nqaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
