loglevel_unencrypted: debug
opsgenie:
    key: ENC[AES256_GCM,data:kv93M92Rgycq8IJtcvdaO1lAZsuq1lJNORVcXEXmGtohTeVY,iv:EVFelyHzg1T0E6hKodtWe+FZ3syd9v4kEQbJ8lpmnTI=,tag:pwcd3oPeys29xJCgUbEyWA==,type:str]
    heartbeat:
        name_unencrypted: xxx.ambari.alert.heartbeat
        interval_unencrypted: 5m
ambari:
    interval_unencrypted: 1m
    url_unencrypted: http://localhost:1337/200/critical
    username_unencrypted: user
    password: ENC[AES256_GCM,data:sl4djw==,iv:KIQuujiyGIihrxt0sM1oYuOrBykCZCQHD12wmtW56zc=,tag:YPF/tgAPUsU1z7zbJzI3lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkvupvkd5a9mtdj4zgrhxqedfjc977a7zkmg37l4x47sadlef3ssesq00g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY0hEVUtqRnY5TzMxanl5
            UHVzendMU0tWRmUxN2JicUVUOW5ualZWdTFZCmFlQjRXZXpSY3hYVlFackYyWGNq
            aVJjcUtDNkphR2xoVFNFM2w1ZXVyVmsKLS0tIGZ5MHZvS2lxUUNvOXlXR0Jrd0Nr
            SDNMWFZ4RTBCaExaVlNHemxzS0VsQm8KSt/QZJMUFkIJlcsBNI8SOSCf8ao5dlrf
            hIztOqs9rOZABsZY8Bmb+/2Hqo+j97PN1igB1HlJ7r1CAN6bSNKgdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T12:01:43Z"
    mac: ENC[AES256_GCM,data:YUBtrYNUqVLZaebZcokszKwbGMWrcZpW2Q0XCPPUavhQkDLVJM0EIjwnjl2/IhSvh97uFU3ol1Otmfnj3ZV/R+cp/bXaVou6DKuaLKH7Sw1oUbpf3erhAeYI5fy+Mkl3kf497colZbio/xtivetkP6vVvWqWkZCTJDN7Xd7T5JI=,iv:hyV3ClUnt3YLkJeF14MNOn46J1e1y1RVDZG4S6nZBJs=,tag:eB6UhlxMFzDHTRFdUKj5fg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
